function OUT = rhoYoungAll(pi)
% Disclaimer: this function was generated by ChatGPT 5.6 SOL and the
% outputs have been checked by the authors for some examples.

% RHOYOUNGALL
%
% Given one permutation pi in one-line notation, compute
% rho_lambda(pi) for every irreducible representation lambda of S_n,
% using Young's orthogonal representation.
%
% INPUT
%
%   pi = [pi(1) ... pi(n)]
%
% Example:
%
%   pi = [3 1 4 2];
%   OUT = rhoYoungAll(pi);
%
% OUTPUT
%
%   OUT(k).lambda
%       Young diagram lambda
%
%   OUT(k).dimension
%       dimension f^lambda of the S_n irrep
%
%   OUT(k).rho
%       small matrix rho_lambda(pi)
%
%   OUT(k).tableaux
%       standard Young tableaux used as basis
%
%
% Convention:
%
%   s_i = (i,i+1)
%
% and right multiplication by s_i swaps positions i and i+1
% in one-line notation.
%
% Therefore, if
%
%   pi = s_i1 s_i2 ... s_ik,
%
% then
%
%   rho_lambda(pi)
%       = rho_lambda(s_i1) ...
%         rho_lambda(s_ik).


%% ============================================================
% 0. Check input
% =============================================================

pi = pi(:).';

n = length(pi);

if ~isequal(sort(pi),1:n)
    error('Input pi must be a permutation of 1:n.');
end


%% ============================================================
% 1. Find all Young diagrams lambda |- n
% =============================================================

partitions = integerPartitions(n);

Nlambda = length(partitions);


%% ============================================================
% 2. Decompose pi into adjacent transpositions
%
%    pi = s_word(1) ... s_word(k)
% =============================================================

word = adjacentWord(pi);


%% ============================================================
% 3. Loop over all Young diagrams
% =============================================================

OUT = struct([]);

for k = 1:Nlambda

    lambda = partitions{k};

    % --------------------------------------------------------
    % Standard Young tableaux of shape lambda
    %
    % These form the basis of the irrep V_lambda.
    % --------------------------------------------------------

    tableaux = standardYoungTableaux(lambda);

    f = length(tableaux);

    % --------------------------------------------------------
    % Construct generators
    %
    % G{i} = rho_lambda(s_i)
    % --------------------------------------------------------

    G = youngGenerators(lambda,tableaux);

    % --------------------------------------------------------
    % Construct rho_lambda(pi)
    % --------------------------------------------------------

    R = eye(f);

    for q = 1:length(word)

        i = word(q);

        R = R * G{i};

    end

    % --------------------------------------------------------
    % Store output
    % --------------------------------------------------------

    OUT(k).lambda = lambda;
    OUT(k).dimension = f;
    OUT(k).rho = R;
    OUT(k).tableaux = tableaux;
    OUT(k).generators = G;

end

end


%% ========================================================================
% INTEGER PARTITIONS
% ========================================================================

function P = integerPartitions(n)

P = partitionRecursive(n,n);

end


function P = partitionRecursive(remaining,maxPart)

if remaining == 0

    P = {[]};
    return

end

P = {};

maxFirst = min(remaining,maxPart);

for first = maxFirst:-1:1

    tails = partitionRecursive(remaining-first,first);

    for j = 1:length(tails)

        P{end+1} = [first tails{j}];

    end

end

end


%% ========================================================================
% STANDARD YOUNG TABLEAUX
% ========================================================================

function tableaux = standardYoungTableaux(lambda)
%
% Generate all standard Young tableaux of shape lambda.
%
% Example:
%
% lambda = [2 1]
%
% gives
%
%   1 2        1 3
%   3 0        2 0
%
% Zero denotes a position outside the Young diagram.

lambda = lambda(:).';

n = sum(lambda);


% -------------------------------------------------------------------------
% Base case
% -------------------------------------------------------------------------

if n == 0

    tableaux = {[]};
    return

end


tableaux = {};


% -------------------------------------------------------------------------
% In a standard Young tableau, the largest entry n must lie
% in a removable corner.
%
% A removable corner is the last box of row r such that
%
%       lambda(r) > lambda(r+1)
%
% with lambda(end+1)=0.
% -------------------------------------------------------------------------

lambdaExt = [lambda 0];

corners = find( ...
    lambdaExt(1:end-1) > lambdaExt(2:end) );


for r = corners

    % Column of the removable corner
    c = lambda(r);

    % ---------------------------------------------------------------------
    % Remove the corner
    % ---------------------------------------------------------------------

    mu = lambda;

    mu(r) = mu(r)-1;

    if ~isempty(mu) && mu(end)==0
        mu(end) = [];
    end

    % ---------------------------------------------------------------------
    % Recursively generate tableaux containing 1,...,n-1
    % ---------------------------------------------------------------------

    smaller = standardYoungTableaux(mu);

    for j = 1:length(smaller)

        Tsmall = smaller{j};

        % Matrix representation of the original Young diagram
        T = zeros(length(lambda),lambda(1));

        if ~isempty(Tsmall)

            T(1:size(Tsmall,1), ...
              1:size(Tsmall,2)) = Tsmall;

        end

        % Put n into the removed corner
        T(r,c) = n;

        tableaux{end+1} = T;

    end

end

end


%% ========================================================================
% YOUNG ORTHOGONAL REPRESENTATION OF ADJACENT TRANSPOSITIONS
% ========================================================================

function G = youngGenerators(lambda,tableaux)
%
% Construct
%
%       G{i} = rho_lambda(s_i)
%
% where
%
%       s_i = (i,i+1).
%
% The basis vectors are the standard Young tableaux.

n = sum(lambda);

f = length(tableaux);


% -------------------------------------------------------------------------
% Create dictionary:
%
%       tableau -> basis index
% -------------------------------------------------------------------------

tabIndex = containers.Map( ...
    'KeyType','char', ...
    'ValueType','double');


for a = 1:f

    tabIndex(tableauKey(tableaux{a})) = a;

end


% -------------------------------------------------------------------------
% Build s_i, i=1,...,n-1
% -------------------------------------------------------------------------

G = cell(n-1,1);


for i = 1:n-1

    R = zeros(f);

    % ---------------------------------------------------------------------
    % Act on every tableau basis vector |T_a>
    % ---------------------------------------------------------------------

    for a = 1:f

        T = tableaux{a};

        % Position of i
        [ri,ci] = find(T==i);

        % Position of i+1
        [rj,cj] = find(T==(i+1));


        % =================================================================
        % Case 1: same row
        %
        % rho(s_i)|T> = +|T>
        % =================================================================

        if ri == rj

            R(a,a) = 1;


        % =================================================================
        % Case 2: same column
        %
        % rho(s_i)|T> = -|T>
        % =================================================================

        elseif ci == cj

            R(a,a) = -1;


        % =================================================================
        % Case 3: different row and column
        %
        % Swapping i and i+1 gives another standard Young tableau.
        % =================================================================

        else

            % -------------------------------------------------------------
            % Content:
            %
            %   content(k) = column(k) - row(k)
            % -------------------------------------------------------------

            content_i = ci-ri;
            content_j = cj-rj;

            % -------------------------------------------------------------
            % Axial distance
            %
            % NOTE:
            % this "dax" is NOT the physical Hilbert-space dimension.
            % -------------------------------------------------------------

            dax = content_j-content_i;

            % Diagonal coefficient
            alpha = 1/dax;

            % Off-diagonal coefficient
            beta = sqrt(1-alpha^2);

            % -------------------------------------------------------------
            % Construct T' by swapping i <-> i+1
            % -------------------------------------------------------------

            Ts = T;

            Ts(ri,ci) = i+1;
            Ts(rj,cj) = i;

            % Find the corresponding tableau basis index
            b = tabIndex(tableauKey(Ts));

            % -------------------------------------------------------------
            % rho(s_i)|T_a>
            %
            %   = alpha |T_a> + beta |T_b>
            % -------------------------------------------------------------

            R(a,a) = alpha;
            R(b,a) = beta;

        end

    end

    G{i} = R;

end

end


%% ========================================================================
% DECOMPOSE A PERMUTATION INTO ADJACENT TRANSPOSITIONS
% ========================================================================

function word = adjacentWord(pi)
%
% Find a sequence
%
%       pi = s_word(1) s_word(2) ... s_word(k)
%
% where
%
%       s_i = (i,i+1).
%
% Convention:
%
% right multiplication by s_i swaps positions i and i+1
% in one-line notation.

n = length(pi);

current = pi;

sortingWord = [];


% -------------------------------------------------------------------------
% Bubble-sort pi to the identity.
%
% If we find
%
%   pi*s_a*s_b*...*s_z = e,
%
% then, since s_i^{-1}=s_i,
%
%   pi = s_z*...*s_b*s_a.
% -------------------------------------------------------------------------

while any(current ~= 1:n)

    % Find first inversion
    i = find( ...
        current(1:end-1) > current(2:end), ...
        1,'first');

    if isempty(i)
        error('Could not decompose permutation.');
    end

    % Right multiplication by s_i:
    % swap positions i and i+1
    current([i i+1]) = current([i+1 i]);

    sortingWord(end+1) = i;

end


% Reverse the sorting sequence
word = fliplr(sortingWord);

end


%% ========================================================================
% TABLEAU KEY
% ========================================================================

function key = tableauKey(T)

key = sprintf('%d_',T(:));

end